;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        anything-execute-extended-command
        anything-exit-minibuffer
        forward-sentence
        mc/mark-all-in-region
        org-force-self-insert
        org-forward-sentence
        org-self-insert-command
        org-seq-end
        org-seq-home
        ruby-end-space
        seq-end
        seq-home
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        ido-dired
        ))
