(loop for (mode . ext) in '((emacs-lisp-mode . "\\.el$")
                            (lisp-mode . "\\.\\(cl\\|lisp\\)$")
                            (scheme-mode . "\\.scm$")
                            (clojure-mode . "\\.clj$")
                            (js-mode . "\\.js$")
                            (coffee-mode . "\\.coffee$")
                            (ruby-mode . "\\.rb$")
                            (org-mode . "\\.org$")
                            (css-mode . "\\.css$")
                            (less-css-mode . "\\.less$")
                            (sass-css-mode . "\\.scss$")
                            (yatex-mode . "\\.tex$")
                            (markdown-mode . "\\.\\(md\\|markdown\\)$"))
      do (add-to-list 'auto-mode-alist (cons ext mode)))

