(-each '((emacs-lisp-mode "\\.el$")
         (emacs-lisp-mode "Cask$")
         (lisp-mode       "\\.\\(cl\\|lisp\\)$")
         (scheme-mode     "\\.scm$")
         (clojure-mode    "\\.clj$")
         (js2-mode        "\\.js$")
         (web-mode        "\\.jsx$")
         (typescript-mode "\\.tsx$")
         (javascript-mode "\\.tern-config$")
         (ruby-mode       "\\.rb$")
         (web-mode        "\\.\\(html\\|tmpl\\)$")
         (css-mode        "\\.css$")
         (scss-mode       "\\.scss$")
         (yatex-mode      "\\.tex$")
         (markdown-mode   "\\.\\(md\\|markdown\\)$"))
  (-lambda ((mode ext)) (add-to-list 'auto-mode-alist (cons ext mode))))
