(-each '((emacs-lisp-mode . "\\.el$")
         (emacs-lisp-mode . "Cask")
         (lisp-mode . "\\.\\(cl\\|lisp\\)$")
         (scheme-mode . "\\.scm$")
         (clojure-mode . "\\.clj$")
         (js-mode . "\\.js$")
         (web-mode . "\\.jsx$")
         (ruby-mode . "\\.rb$")
         (css-mode . "\\.css$")
         (scss-mode . "\\.scss$")
         (yatex-mode . "\\.tex$")
         (markdown-mode . "\\.\\(md\\|markdown\\)$"))
  (lambda (dlst) (add-to-list 'auto-mode-alist
                              (cons (rest dlst) (first dlst)))))
